### ISSUE TITLE
Using Stripe as Payment Method

### ISSUE THREAD

**Issue by robtec** [vendurehq/storefront-angular-starter#81]
Hi,

I've configured my vendure server to use Stripe as a payment back-end but cannot get my storefront to use it

```
error 3/31/23, 3:41 PM - [Vendure Server] CreatePayment is not allowed for apiType 'shop'
Error: CreatePayment is not allowed for apiType 'shop'
    at PaymentMethodHandler.createPayment [as createPaymentFn] (/usr/src/app/node_modules/@vendure/payments-plugin/package/stripe/stripe.handler.js:27:19)
    at PaymentMethodHandler.createPayment (/usr/src/app/node_modules/@vendure/core/dist/config/payment/payment-method-handler.js:77:42)
    at PaymentService.createPayment (/usr/src/app/node_modules/@vendure/core/dist/service/services/payment.service.js:91:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async OrderService.addPaymentToOrder (/usr/src/app/node_modules/@vendure/core/dist/service/services/order.service.js:807:25)
    at async ShopOrderResolver.addPaymentToOrder (/usr/src/app/node_modules/@vendure/core/dist/api/resolvers/shop/shop-order.resolver.js:182:31)
```

Does the angular store front support Stripe?

**Comment by michaelbromley** [comment]
Hi,

Yes, stripe will work with this storefront, but it works slightly differently. You don't directly call `addPaymentToOrder` - see the docs for more info: https://www.vendure.io/docs/typescript-api/payments-plugin/stripe-plugin/#storefront-usage
